//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SAHIBINDENDBEntities : DbContext
    {
        public SAHIBINDENDBEntities()
            : base("name=SAHIBINDENDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TABLE_ADVERT> TABLE_ADVERT { get; set; }
        public virtual DbSet<TABLE_SEARCH_DETAIL> TABLE_SEARCH_DETAIL { get; set; }
        public virtual DbSet<TABLE_SEARCH_MASTER> TABLE_SEARCH_MASTER { get; set; }
        public virtual DbSet<TABLE_SEARCHABLE_TYPE> TABLE_SEARCHABLE_TYPE { get; set; }
        public virtual DbSet<VIEW_NOTIFICATION> VIEW_NOTIFICATION { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_GETSEARCHURL(Nullable<int> iD, Nullable<int> pAGE)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GETSEARCHURL", iDParameter, pAGEParameter);
        }
    }
}
