//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_ADVERT
    {
        public int ID { get; set; }
        public int AdvertID { get; set; }
        public string Description { get; set; }
        public string ThumbnailLink { get; set; }
        public string Location { get; set; }
        public System.DateTime AdvertDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int SearchMasterID { get; set; }
        public int Price { get; set; }
        public bool IsSeen { get; set; }
        public Nullable<int> Size { get; set; }
        public string Room { get; set; }
        public string Heating { get; set; }
    
        public virtual TABLE_SEARCH_MASTER TABLE_SEARCH_MASTER { get; set; }
    }
}
