//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_SEARCH_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TABLE_SEARCH_MASTER()
        {
            this.TABLE_ADVERT = new HashSet<TABLE_ADVERT>();
            this.TABLE_SEARCH_DETAIL = new HashSet<TABLE_SEARCH_DETAIL>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public int AdvertTypeID { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLE_ADVERT> TABLE_ADVERT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLE_SEARCH_DETAIL> TABLE_SEARCH_DETAIL { get; set; }
        public virtual TABLE_ADVERT_TYPE TABLE_ADVERT_TYPE { get; set; }
    }
}
