//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_SEARCH_DETAIL
    {
        public int ID { get; set; }
        public int SearchMasterID { get; set; }
        public int SearchableTypeID { get; set; }
        public string SearchableValue { get; set; }
    
        public virtual TABLE_SEARCH_MASTER TABLE_SEARCH_MASTER { get; set; }
        public virtual TABLE_SEARCHABLE_TYPE TABLE_SEARCHABLE_TYPE { get; set; }
    }
}
